<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class VarianSeeder extends Seeder
{
    /**
     * Run the seeder.
     *
     * @return void
     */
    public function run()
    {
        $varians = [
            [
                'mobil_id' => 1, // Toyota Avanza
                'nama' => 'Avanza 1.5 G CVT',
                'kode' => 'G',
                'deskripsi' => 'Varian premium Toyota Avanza dengan transmisi CVT, menawarkan kenyamanan dan efisiensi untuk keluarga.',
                'harga_otr' => 272500000.00,
                'tipe_mesin' => 'bensin',
                'kapasitas_mesin_cc' => 1496,
                'silinder' => 4,
                'transmisi' => 'cvt',
                'jumlah_gigi' => null,
                'daya_hp' => 104,
                'torsi_nm' => 137,
                'jenis_bahan_bakar' => 'Bensin',
                'konsumsi_bahan_bakar_kota' => 12.50,
                'konsumsi_bahan_bakar_jalan' => 18.40,
                'panjang_mm' => 4395,
                'lebar_mm' => 1730,
                'tinggi_mm' => 1700,
                'jarak_sumbu_roda_mm' => 2750,
                'ground_clearance_mm' => 195,
                'berat_kosong_kg' => 1155,
                'berat_isi_kg' => 1710,
                'kapasitas_bagasi_l' => 547,
                'kapasitas_tangki_l' => 43,
                'akselerasi_0_100_kmh' => 13.50,
                'kecepatan_maksimal_kmh' => 170,
                'fitur_keamanan' => json_encode(['ABS', 'EBD', 'Airbag Pengemudi', 'Airbag Depan', 'Alarm & Immobilizer', 'Sabuk Pengaman 3 Titik', 'ISOFIX']),
                'fitur_kenyamanan' => json_encode(['AC', 'Power Steering', 'Power Window', 'Central Lock', 'Keyless Entry', 'Push Start Button', 'Armrest']),
                'fitur_hiburan' => json_encode(['Radio', 'USB Port', 'Bluetooth', 'Touchscreen Head Unit', 'Speaker']),
                'aktif' => true,
            ],
            [
                'mobil_id' => 2, // Honda Brio
                'nama' => 'Brio RS CVT',
                'kode' => 'RS',
                'deskripsi' => 'Varian sporty Honda Brio dengan desain modern dan transmisi CVT, ideal untuk penggunaan perkotaan.',
                'harga_otr' => 243900000.00,
                'tipe_mesin' => 'bensin',
                'kapasitas_mesin_cc' => 1199,
                'silinder' => 4,
                'transmisi' => 'cvt',
                'jumlah_gigi' => null,
                'daya_hp' => 89,
                'torsi_nm' => 110,
                'jenis_bahan_bakar' => 'Bensin',
                'konsumsi_bahan_bakar_kota' => 16.50,
                'konsumsi_bahan_bakar_jalan' => 22.00,
                'panjang_mm' => 3815,
                'lebar_mm' => 1680,
                'tinggi_mm' => 1485,
                'jarak_sumbu_roda_mm' => 2405,
                'ground_clearance_mm' => 165,
                'berat_kosong_kg' => 975,
                'berat_isi_kg' => 1350,
                'kapasitas_bagasi_l' => 258,
                'kapasitas_tangki_l' => 35,
                'akselerasi_0_100_kmh' => 12.80,
                'kecepatan_maksimal_kmh' => 160,
                'fitur_keamanan' => json_encode(['ABS', 'EBD', 'Airbag Pengemudi', 'Airbag Depan', 'Alarm & Immobilizer', 'Sabuk Pengaman 3 Titik']),
                'fitur_kenyamanan' => json_encode(['AC', 'Power Steering', 'Power Window', 'Central Lock', 'Keyless Entry']),
                'fitur_hiburan' => json_encode(['Radio', 'USB Port', 'Bluetooth', 'Touchscreen Head Unit', 'Speaker']),
                'aktif' => true,
            ],
            [
                'mobil_id' => 3, // Hyundai Ioniq 5
                'nama' => 'Ioniq 5 Signature Long Range',
                'kode' => 'Signature',
                'deskripsi' => 'Varian premium Hyundai Ioniq 5 dengan jangkauan baterai jauh dan fitur teknologi canggih.',
                'harga_otr' => 870000000.00,
                'tipe_mesin' => 'listrik',
                'kapasitas_mesin_cc' => null,
                'silinder' => null,
                'transmisi' => 'automatic',
                'jumlah_gigi' => 1,
                'daya_hp' => 225,
                'torsi_nm' => 350,
                'jenis_bahan_bakar' => 'Listrik',
                'konsumsi_bahan_bakar_kota' => null,
                'konsumsi_bahan_bakar_jalan' => null,
                'panjang_mm' => 4635,
                'lebar_mm' => 1890,
                'tinggi_mm' => 1605,
                'jarak_sumbu_roda_mm' => 3000,
                'ground_clearance_mm' => 160,
                'berat_kosong_kg' => 2010,
                'berat_isi_kg' => 2450,
                'kapasitas_bagasi_l' => 531,
                'kapasitas_tangki_l' => null,
                'akselerasi_0_100_kmh' => 7.40,
                'kecepatan_maksimal_kmh' => 185,
                'fitur_keamanan' => json_encode(['ABS', 'EBD', 'BA', 'VSC', 'TCS', 'Hill Start Assist', 'Airbag Pengemudi', 'Airbag Depan', 'Airbag Samping', 'Airbag Tirai', 'Alarm & Immobilizer', 'ISOFIX', 'Kamera Parkir', 'Sensor Parkir']),
                'fitur_kenyamanan' => json_encode(['AC Dual Zone', 'Power Steering', 'Electric Mirror', 'Power Window', 'Central Lock', 'Keyless Entry', 'Push Start Button', 'Cruise Control', 'Auto Rain Sensor', 'Auto Light', 'Electric Seat', 'Leather Seat', 'Armrest']),
                'fitur_hiburan' => json_encode(['Radio', 'USB Port', 'Bluetooth', 'Apple CarPlay', 'Android Auto', 'Touchscreen Head Unit', 'Speaker', 'Steering Switch']),
                'aktif' => true,
            ],
            [
                'mobil_id' => 4, // Mitsubishi Xpander
                'nama' => 'Xpander Ultimate CVT',
                'kode' => 'Ultimate',
                'deskripsi' => 'Varian tertinggi Mitsubishi Xpander dengan fitur lengkap dan transmisi CVT, ideal untuk keluarga.',
                'harga_otr' => 312500000.00,
                'tipe_mesin' => 'bensin',
                'kapasitas_mesin_cc' => 1499,
                'silinder' => 4,
                'transmisi' => 'cvt',
                'jumlah_gigi' => null,
                'daya_hp' => 104,
                'torsi_nm' => 141,
                'jenis_bahan_bakar' => 'Bensin',
                'konsumsi_bahan_bakar_kota' => 13.20,
                'konsumsi_bahan_bakar_jalan' => 18.50,
                'panjang_mm' => 4475,
                'lebar_mm' => 1750,
                'tinggi_mm' => 1730,
                'jarak_sumbu_roda_mm' => 2775,
                'ground_clearance_mm' => 205,
                'berat_kosong_kg' => 1240,
                'berat_isi_kg' => 1780,
                'kapasitas_bagasi_l' => 495,
                'kapasitas_tangki_l' => 45,
                'akselerasi_0_100_kmh' => 14.00,
                'kecepatan_maksimal_kmh' => 170,
                'fitur_keamanan' => json_encode(['ABS', 'EBD', 'BA', 'Airbag Pengemudi', 'Airbag Depan', 'Alarm & Immobilizer', 'ISOFIX', 'Sabuk Pengaman 3 Titik']),
                'fitur_kenyamanan' => json_encode(['AC', 'Power Steering', 'Power Window', 'Central Lock', 'Keyless Entry', 'Push Start Button', 'Armrest']),
                'fitur_hiburan' => json_encode(['Radio', 'USB Port', 'Bluetooth', 'Touchscreen Head Unit', 'Speaker']),
                'aktif' => true,
            ],
            [
                'mobil_id' => 5, // Wuling Air ev
                'nama' => 'Air ev Long Range',
                'kode' => 'Long Range',
                'deskripsi' => 'Varian Wuling Air ev dengan jangkauan baterai lebih jauh, cocok untuk mobilitas perkotaan.',
                'harga_otr' => 299000000.00,
                'tipe_mesin' => 'listrik',
                'kapasitas_mesin_cc' => null,
                'silinder' => null,
                'transmisi' => 'automatic',
                'jumlah_gigi' => 1,
                'daya_hp' => 41,
                'torsi_nm' => 110,
                'jenis_bahan_bakar' => 'Listrik',
                'konsumsi_bahan_bakar_kota' => null,
                'konsumsi_bahan_bakar_jalan' => null,
                'panjang_mm' => 2974,
                'lebar_mm' => 1505,
                'tinggi_mm' => 1631,
                'jarak_sumbu_roda_mm' => 2010,
                'ground_clearance_mm' => 150,
                'berat_kosong_kg' => 880,
                'berat_isi_kg' => 1120,
                'kapasitas_bagasi_l' => 200,
                'kapasitas_tangki_l' => null,
                'akselerasi_0_100_kmh' => 20.00,
                'kecepatan_maksimal_kmh' => 100,
                'fitur_keamanan' => json_encode(['ABS', 'EBD', 'Airbag Pengemudi', 'Airbag Depan', 'Alarm & Immobilizer', 'ISOFIX', 'Kamera Parkir', 'Sensor Parkir']),
                'fitur_kenyamanan' => json_encode(['AC', 'Power Steering', 'Power Window', 'Central Lock', 'Keyless Entry']),
                'fitur_hiburan' => json_encode(['Radio', 'USB Port', 'Bluetooth', 'Touchscreen Head Unit', 'Speaker']),
                'aktif' => true,
            ],
        ];

        foreach ($varians as $varian) {
            DB::table('varians')->insert([
                'mobil_id' => $varian['mobil_id'],
                'nama' => $varian['nama'],
                'kode' => $varian['kode'],
                'deskripsi' => $varian['deskripsi'],
                'harga_otr' => $varian['harga_otr'],
                'tipe_mesin' => $varian['tipe_mesin'],
                'kapasitas_mesin_cc' => $varian['kapasitas_mesin_cc'],
                'silinder' => $varian['silinder'],
                'transmisi' => $varian['transmisi'],
                'jumlah_gigi' => $varian['jumlah_gigi'],
                'daya_hp' => $varian['daya_hp'],
                'torsi_nm' => $varian['torsi_nm'],
                'jenis_bahan_bakar' => $varian['jenis_bahan_bakar'],
                'konsumsi_bahan_bakar_kota' => $varian['konsumsi_bahan_bakar_kota'],
                'konsumsi_bahan_bakar_jalan' => $varian['konsumsi_bahan_bakar_jalan'],
                'panjang_mm' => $varian['panjang_mm'],
                'lebar_mm' => $varian['lebar_mm'],
                'tinggi_mm' => $varian['tinggi_mm'],
                'jarak_sumbu_roda_mm' => $varian['jarak_sumbu_roda_mm'],
                'ground_clearance_mm' => $varian['ground_clearance_mm'],
                'berat_kosong_kg' => $varian['berat_kosong_kg'],
                'berat_isi_kg' => $varian['berat_isi_kg'],
                'kapasitas_bagasi_l' => $varian['kapasitas_bagasi_l'],
                'kapasitas_tangki_l' => $varian['kapasitas_tangki_l'],
                'akselerasi_0_100_kmh' => $varian['akselerasi_0_100_kmh'],
                'kecepatan_maksimal_kmh' => $varian['kecepatan_maksimal_kmh'],
                'fitur_keamanan' => $varian['fitur_keamanan'],
                'fitur_kenyamanan' => $varian['fitur_kenyamanan'],
                'fitur_hiburan' => $varian['fitur_hiburan'],
                'aktif' => $varian['aktif'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}